### ISSUE TITLE
Missing module: myMiniCam2 from scene.cameras

### ISSUE THREAD

**Issue by loongfeili** [ziweny11/PhotoRegCodes#1]
> ImportError: cannot import name 'myMiniCam2' from 'scene.cameras

Thank you for your great work! 
But how can I find this module  when I run `python main.py` ? 
Thank you.

**Comment by ziweny11** [comment]
Hi NimbusLongfei, thanks for your interest! we've just release the code with the paper. We're actively cleaning the code up. Hopefully done by 10/13

**Comment by loongfeili** [comment]
thank you

**Comment by ziweny11** [comment]
Hi I just uploaded new environment and code. They should include missing module. Sorry for causing inconvenience!
