### ISSUE TITLE
More detailed code environment configuration information is needed.

### ISSUE THREAD

**Issue by misakamage** [ziweny11/PhotoRegCodes#2]
Thank you for open-sourcing this great work. Could you please provide detailed code environment configuration information, including the Python version, CUDA version, Torch version, and so on? Additionally, I hope you can also provide some sample data. Also, do the source codes for 3dgs and dust3r need to be downloaded into this project folder? There are many points in the README that confuse me.

**Comment by ziweny11** [comment]
Hi I just uploaded new environment and code. They should include missing module. Sorry for causing inconvenience!
The environment is a merge of 3DGS's and dust3r's; I will provide some sample data after organizing; for the new version, no need to download source code of 3dgs and dust3r into the folder; I will keep the repo updated.

**Comment by misakamage** [comment]
OK，thank you for your help!
